# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/william/GitHub/codeEasi/convertor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SAI_SQL = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.SAI_SQL.setGeometry(QtCore.QRect(10, 10, 781, 291))
        self.SAI_SQL.setObjectName("SAI_SQL")
        self.SAI_WD = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.SAI_WD.setGeometry(QtCore.QRect(10, 310, 781, 261))
        self.SAI_WD.setObjectName("SAI_WD")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda : self.SQL2WD())
        self.pushButton.setGeometry(QtCore.QRect(220, 580, 391, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SQL Convertor"))
        self.pushButton.setText(_translate("MainWindow", "Convertir"))

    def SQL2WD(self):
        SQL = self.SAI_SQL.toPlainText()
        text = SQL.split("\n")
        text_len = len(text)

        new_text = ""
        
        for x, line in enumerate(text):
            if x < text_len - 1:
                new_text += '"' + line + '" + RC + ...' + "\n"
            else:  
                new_text += '"' + line + '"' + "\n"

        self.SAI_WD.setPlainText(new_text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
